### ISSUE TITLE
Changing to a new tab erases all images from the voice bar

### ISSUE THREAD

**Issue by r03ert0** [ConnectProject/mavoix-app#39]
Changing to a new tab erases all images from the voice bar, making it impossible to have images from different tabs.

Observed: open the app, put images from the first tab in the voice bar, move to another tab, the images from the voice bar disappear.
Expected: the images should stay in place.

**Comment by ntraut** [comment]
This issue appeared on commit f345b5772305074ba28c16be5625d850c30d311a. I thought it was a good idea to use a computed property to get the list of active items, in that way we don't have to manage both the fact if the item is active and the list of active items, but the problem is that the items are reloaded each time we change tab.

Maybe a better solution would be to use a computed property to tell if the item is active, and maintain the list of active items.

**Comment by morvanr** [comment]
I guess this one is fixed right ?
